<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>55e57dac-2207-459f-b640-6affe41724e8</testSuiteGuid>
   <testCaseLink>
      <guid>fcc8cd1e-984f-4776-bc09-8c857a36edcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/TC05_Login 05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17226b4b-e1c2-42ac-a946-ca798d674f6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d750cd06-1c5d-4867-a64f-9cae0f942bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/TC04_Login 04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0c3d1d9-497f-4da7-90fb-da2bdb4823f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4976c2e3-a0db-47fd-8483-f4f268a4e4c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/TC03_Login 03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f7deb60-cc98-45bc-935c-ae83202138fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f710d3a7-e752-4bfa-9fca-e55e61dc2528</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/TC02_Login 02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aca884ad-ee10-42fd-92e0-c4f90137f809</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>810c72a5-2e7e-472d-a54b-0a4fd9177b85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/TC01_Load Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ddf2b40-d02b-41e0-95dc-8d719817ebcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585ed65c-7f52-47be-8343-5dc5e5033c52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86bf638a-e118-4d97-9128-fbdfa3e312d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84bf8359-93d5-4d26-91d3-dbf3e86a3bba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88225b5b-0f06-4d18-9099-b16ccb79987e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630e3add-a4eb-4eb1-b63c-901f3b8d1cc0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
