<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Previous video_yt-spec-touch-feedback-s_9114cf</name>
   <tag></tag>
   <elementGuidId>9821461f-67b3-4c78-bb2f-ea8831302291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigation-button-down']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.yt-spec-touch-feedback-shape.yt-spec-touch-feedback-shape--down.yt-spec-touch-feedback-shape--touch-response > div.yt-spec-touch-feedback-shape__fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02093562-ebf5-4be2-bf00-304c9a969da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-spec-touch-feedback-shape__fill</value>
      <webElementGuid>78eab4a2-3863-401b-a724-596b83c3b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-button-down&quot;)/ytd-button-renderer[@class=&quot;style-scope ytd-shorts&quot;]/yt-button-shape[1]/button[@class=&quot;yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-xl yt-spec-button-shape-next--icon-button yt-spec-button-shape-next--enable-backdrop-filter-experiment&quot;]/yt-touch-feedback-shape[1]/div[@class=&quot;yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--down yt-spec-touch-feedback-shape--touch-response&quot;]/div[@class=&quot;yt-spec-touch-feedback-shape__fill&quot;]</value>
      <webElementGuid>216b2a18-a201-41ef-8007-f9e55cb05422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-button-down']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>f08f1b54-ac63-4ea0-897b-f34cf0f496cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>65bb436d-167c-46d6-83eb-e0fb88c27d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
