<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Preview_yt-spec-touch-feedback-shape__fill</name>
   <tag></tag>
   <elementGuidId>4f2da83a-bdbf-4180-89eb-d9361be7a185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigation-button-down']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.yt-spec-touch-feedback-shape.yt-spec-touch-feedback-shape--down.yt-spec-touch-feedback-shape--touch-response > div.yt-spec-touch-feedback-shape__fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d0bb317-d489-48cc-b84f-4a0728efb4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-spec-touch-feedback-shape__fill</value>
      <webElementGuid>8eb9ff64-c2e4-4336-b460-b46e676cd6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-button-down&quot;)/ytd-button-renderer[@class=&quot;style-scope ytd-shorts&quot;]/yt-button-shape[1]/button[@class=&quot;yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-xl yt-spec-button-shape-next--icon-button yt-spec-button-shape-next--enable-backdrop-filter-experiment&quot;]/yt-touch-feedback-shape[1]/div[@class=&quot;yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--down yt-spec-touch-feedback-shape--touch-response&quot;]/div[@class=&quot;yt-spec-touch-feedback-shape__fill&quot;]</value>
      <webElementGuid>1ba27159-fef6-4844-a7dd-164b2537774e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-button-down']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>30e08565-972b-4175-b36a-66817229d0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>88e91731-9aff-49c1-a147-74becb93a436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
